# This playbook is for Amazon Linux
- hosts: targets
  become: yes
  gather_facts: no
  vars:
    locale: ja_JP.UTF-8
    zone: Asia/Tokyo
    zoneinfo_path: /usr/share/zoneinfo/Asia/Tokyo
  tasks:
    - name: set locale to /etc/cloud/cloud.cfg
      lineinfile: 'dest=/etc/cloud/cloud.cfg line="locale: {{locale}}"'
    - name: set locale
      command: localectl set-locale LANG=ja_JP.UTF-8
    - name: set localtime
      command: timedatectl set-timezone Asia/Tokyo
    - name: set set-keymap
      command: localectl set-keymap jp106
    - name: yum update
      yum: state=latest name=*
    - name: install zsh
      yum: name=zsh state=installed
    - name: install util-linux-user
      yum: name=util-linux-user state=installed
    - name: set zsh as default shell for ec2user
      command: chsh -s '/bin/zsh' ec2-user
    - name: install request packeges
      yum: name={{ item }} state=installed
      with_items:
          - gcc-c++
          - glibc-headers
          - git
          - openssl-devel
          - libyaml-devel
          - readline-devel
          - zlib-devel
          - libjpeg-devel
          - libpng-devel
          - ImageMagick
          - ImageMagick-devel
          - libxml2-devel
          - libxslt-devel
